### ISSUE TITLE
AI(artificial intelligence) 세미나

### ISSUE THREAD

**Issue by littlesoo** [kovidev/weps#10]
학교 방학기간(12~2월)에 사내에서 AI 세미나를 진행할까합니다.

AI의 개요.
Machine Learning
Deep Learning 

정도의 순서로 진행하며, Deep Learning 위주가 되지 않을까 싶네요.

참석희망해 주세요.(희망댓글의 수에 따라 진행여부는 결정합니다.^^)

**Comment by youchangCho** [comment]
난이도가 어떻게 되는지 궁금 합니다. 
혹시 구체적인 세미나 계획이 있으시면 올려주시길 바랍니다.
선행 학습이 필요하지 않을까 싶은데요. 
사실 말만 듣고 기본 로직만 알지 분야가 다르다 보니 '이런식으로 하는가 보구나~' 하고만 있어서 세미나 할 경우 뒤처질까봐 걱정이 됩니다^^;

**Comment by littlesoo** [comment]
선행학습을 하면 물론 좋겠지만, 안해도 큰 지장은 없을듯 하네요.
AI의 개요 및 Machine Learning, Deep Learning 에서 사용하는 모델에 대한 이론적인 이해가 세미나 내용일겁니다. 진도와 이해여부에 따라 실제 예제까지 진행할 수 도 있구요.ㅋ
주로 내가 chapter별 교육을 시켜주는 방식일 듯 하네요.

**Comment by youchangCho** [comment]
그렇다면 전 세미나 찬성 입니다.

**Comment by jungbyung** [comment]
참석희망합니다!

**Comment by taeminhong** [comment]
업무 개선안이나 문제 제기와 관련 없는 이슈는 닫습니다.
하지만 이왕 진행한 설문조사이기 때문에 12월 15일까지 한시적으로 열어두겠습니다.

**Comment by Dongjun-colt** [comment]
저도 참석 희망합니다.

**Comment by SeungHoAhn** [comment]
참석 희망합니다.^^
