### ISSUE TITLE
오직 한 사람만이 저장소를 만들 권한을 갖는 것이 좋겠습니다.

### ISSUE THREAD

**Issue by taeminhong** [kovidev/weps#11]
저장소를 아무나, 아무렇게나 만들기 때문에 여러 문제가 산재합니다.

- 백업을 못 합니다. 저장소를 만들면 바로 미러링을 수행해야 하는데 관리자는 저장소가 생겼다는 사실조차 알지 못합니다.
- 프로젝트의 메인 저장소 주소를 몰라 시간을 낭비하는 일이 허다합니다.
- 잘못 만들거나 버려지는 저장소가 생깁니다.
- 각 저장소 담당자가 누군지 불분명하므로 인수인계에 차질이 있습니다.
- 서브버전 서버에 오류가 생깁니다.

저장소 생성 권한을 한 사람에게 양도하고 오직 그 사람을 통해서만 저장소를 만들도록 강제해야 합니다.
저장소를 만들어달라고 요청할 때는 반드시 저장소의 목적과 담당자, 주요 도구 등을 명시하도록 하면 원활한 저장소 관리가 가능하고 나중에 쓸데없이 시간을 낭비하는 일을 피할 수 있습니다.

(Updated)
개발 도구를 명시하면 유니티 파편화(#5)도 완화할 수 있습니다.

**Comment by childmild** [comment]
전에 있던 웹팀 svn 같은 부분은 이기회에 서버가 통합 되는것인지 아니면 분리하여관리하는지 여부와  svn 관리자가 기존 웹팀 svn 도 관리해야하는지 여부도 생각해 봐야할것같습니다. 그리고 프로젝트들 중에서 서브버전 에 등록조차 되지 않고 코드로드 인수인계로만 관리되고있는 프로젝트들도있는데 이기회에 다 등록해야하지 않을까 싶습니다.

**Comment by taeminhong** [comment]
저장소 서버는 하나여야 합니다. 안 그러면 관리가 안 되겠죠?
서버 통합은 구 차장 복귀 후에 하겠습니다.
저에겐 웹 팀 서브버전 서버 접근 권한이 없거든요.
