### ISSUE TITLE
보안 점검 및 강화 안건

### ISSUE THREAD

**Issue by Dongjun-colt** [kovidev/weps#14]
개발팀 모두 백신을 구동해서 시스템 검사를 해야 할 듯합니다. 개인 PC뿐만 아니라 서버도 점검이 필요합니다.

2018-01-16 19:50경 특정 PC에서 BTC 랜섬웨어로 의심되는 프로그램이 설치되어 비트코인 채굴 프로그램의 동작과 함께 모든 데이터가 락이 걸렸습니다.
이후 2018-01-17 05:00 경 추가 프로그램 설치 증상도 관찰되었습니다.

EDITED:  내용을 짧게 요약했습니다.

**Comment by taeminhong** [comment]
윈도우 XP를 구동하는 60.196.157.176 에서도 다수의 바이러스가 있었습니다.

**Comment by gegabal** [comment]
V3나 윈도우 디펜더로 검사 및 치료가 가능한가요?

**Comment by taeminhong** [comment]
해당 PC는 포맷한 상태로 디펜더나 V3로 검출이나 치료가 가능한지는 확인되지 않았습니다.
일단 모두 윈도우 디펜더를 활성화 해주세요. V3 설치를 원하시는 분은 저에게 하이웍스로 말씀해주세요.

**Comment by YunkiKim** [comment]
해당 하드는 보관중이구요. 현재 V3로 검출이 가능한지 테스트 중에 있습니다.
