### ISSUE TITLE
커밋 메시지 생략 금지

### ISSUE THREAD

**Issue by taeminhong** [kovidev/weps#16]
커밋 메시지를 쓰지 않으면 커밋이 안 되게 하는게 좋겠습니다.

종종 실수로 확인 버튼을 눌러서 의도치 않게 커밋하는 것을 방지하기도 하고요.
커밋 메시지 작성에 더 신경을 쓰게 유도하는 효과도 있을 것으로 기대합니다.

**Comment by jeonjongku** [comment]
메세지 없인 커밋 안되게 하는 의견에 아주 찬성합니다

**Comment by gegabal** [comment]
OK.

**Comment by SeungHoAhn** [comment]
네 좋습니다.!

**Comment by taeminhong** [comment]
서버에 반영했습니다.
