### ISSUE TITLE
제안: 월간활동내역서를 구글문서로 이전

### ISSUE THREAD

**Issue by taeminhong** [kovidev/weps#3]
매월 초에 작성하는 활동내역서를 구글 문서로 이전하면 보고자와 피보고자 모두 노고를 덜 수 있고 부가적인 이득도 얻을 수 있습니다.

# 동기

현행 활동 내역서 작성 과정은 다음과 같습니다.

- 피보고자가 템플릿 문서를 모든 보고자에게 메일로 송부
- 보고자는 자신의 영역에 값을 채워 넣고 반송
- 피보고자는 모든 문서를 병합

이 과정에서 번거로운 파일 전송이 계속 반복되며 병합과정에 많은 시간이 소요됩니다.
문서를 공유하면 이런 불편함을 없앨 수 있습니다.

# 해결책

피고보자는 활동내역서를 구글 문서로 올리고 보고자에게 공유 권한을 줍니다.
보고자는 각자 자신의 영역에 값을 채워 넣습니다. 이 작업은 몰아서 할 수도 있고 매일 그 날의 분량을 미리 채워 넣는 것도 가능합니다.
피보고자는 달마다 보고자에게 필드를 채워달라고 요청하고 나중에 필드가 다 채워졌는지만 확인하면 됩니다.

# 근거

공유문서를 만드는 방법은 여러 가지가 있습니다.
윈도에서 제공하는 파일 공유시스템도 있고 [Dropbox](https://www.dropbox.com/)를 쓸 수도 있습니다.
엑셀 온라인과 구글 문서같은 웹앱도 많이 활성화되어있습니다.
그중에서 구글 문서가 가장 효과적입니다. 그 이유는 아래와 같습니다.

- 어떤 네트워크에서도 사용할 수 있습니다. 내부망으로 제한되지 않습니다.
- 무료입니다.
- 안전합니다. 실수를 저지르더라도 언제든 되돌릴 수 있습니다.
- 엑셀을 설치하지 않아도 쓸 수 있습니다.
- 웹 스프레드시트 앱 중에서 가장 많은 기능을 가지며 호환성이 뛰어납니다.
- 파일 전송이 없으므로 바이러스가 퍼질 경로를 차단합니다.
- 모바일 환경에서도 사용할 수 있습니다.

# 참조 구현

아산 병원 공간관리 프로젝트팀은 이미 몇 개월 전부터 [공유 문서](https://docs.google.com/spreadsheets/d/1WQhFXeTYK3Jd9WkPON445bbz2Whjg4eVcLVnUYlDkXA/edit?usp=sharing)를 사용해서 효과를 보았습니다.

솔루션 개발 2팀은 [엑셀 온라인](https://1drv.ms/x/s!Alb0UmRtXlm6mDNUTBfVSVkLJ1No)을 이용해서 비슷한 효과를 얻고 있습니다.

**Comment by youchangCho** [comment]
현 이슈에 동의 합니다. 
이 시스템을 유지 해야 한다면 위 방식으로 하는게 가장 좋을 거라는 의견 입니다.
월말 바쁜 일정으로 제출 일자가 늦어진 경험이 많습니다.
메일로 받은 후 다시 발송 해야 하는 부담이 줄어 듭니다.

**Comment by gegabal** [comment]
좋은 의견입니다.
여기에 제 의견을 덧붙이자면..
꼭 구글독스로 한정 지을 필요는 없어보입니다.  
제가 엑셀온라인을 사용하기 때문에 만은 아니며 아래와 같은 나름 합당한 이유가 있습니다.

보고자 입장에서는 URL 열고 작성하면 끝이니 플렛폼이 뭐가되던 동일한 공수 일테고요
피보고자가 실제로 문서를 생성하고 관리하게 되기에 추가 공수가 발생하는 상황인데..

피보고자인 저의 프로세스를 보면
작업PC에 OneDrive 어플이 설치되어 있기 떄문에 윈도우 탐색기를 통해 엑셀문서만 올려놓으면 
문서 공유가 끝나는 프로세스 입니다. 물론 공유 URL은 메일로 보내야 겠지만.. 

결론은.
구글독스던 MS온라인 이던.. 어느 하나 나쁜건 없으니..
피보고자가 사용하기에 편한 온라인문서 방식을 채택하자는 의견 입니다.

**Comment by taeminhong** [comment]
@gegabal 네. 엑셀 온라인과 구글 문서는 거의 같은 방식으로 작동합니다.
특히 OneDrive와의 연동은 엑셀 온라인의 장점이죠.
근데 한 가지 걸리는 점이 있는데 [엑셀 온라인은 시트 복제를 못 합니다](https://support.office.com/en-us/article/Can-I-copy-a-worksheet-in-the-current-workbook-5d8109a7-cba1-474f-b835-11cd89da99c0).
예를 들면 12월 활동 내역 시트를 만들 때 11월 시트를 복제한 다음, 필드를 비우면 간단한데 그게 안 됩니다. 위 링크에서 말하는 대로 새 시트를 만들고 이전 시트 내용을 복사해서 붙여넣어야 합니다.
구글 문서는 시트 복제가 쉬워서 아산 병원 공간관리팀은 굳이 피보고자가 아니라도 아무나 필요한 시트를 만들어 놓기가 좋았습니다.

**Comment by gegabal** [comment]
@taeminhong 그렇죠 근데 어짜피 OneDrive위에서 사용할때는 그냥 엑셀 열고 시트 추가하면 됐었으니까. 여튼 온라인문서 방식으로 가게 되면 이제 피보고자는 부장님 하나면 되니 부장님 의견을 들어보는걸로.

**Comment by childmild** [comment]
전 찬성합니다 
나중에 차트 및 통계기능을 이용하면 더욱좋은 자료를 출력할수도 있을거같고
작성 몰리는시간에도 유져가 동시 작성도 가능하다는 점에서 좋은거같습니다.

**Comment by taeminhong** [comment]
구글 문서를 시험 운영중입니다.
[여기에](https://docs.google.com/spreadsheets/d/1TSKV4FSAb0yPv5c-iiacok-bPSM3mkq8af1P5e-k2fk/edit?usp=sharing) 접속해서 사용해보세요.
