### ISSUE TITLE
제안 : 오랜된 서적 정리를 건의 합니다.

### ISSUE THREAD

**Issue by youchangCho** [kovidev/weps#4]
연구소 내부 곳곳에 비치된 오래된 (보지 않는) 서적에 대한 정리를 제안 합니다.

**Comment by taeminhong** [comment]
특정 언어나 API, 도구를 다루는 책은 지금 당장 폐기 처분해도 상관없다고 생각합니다.
시대에 뒤떨어진 내용을 다뤄서 도움이 전혀 안 되고 오히려 해만 되거든요.
대신 시대가 변해도 가치가 떨어지지 않는 몇몇 서적이 있습니다.
알고리즘, 테스트 가이드 등이 이에 해당합니다.
폐기 대상을 한곳에 모아서 목록을 만드는 작업을 해야 할 듯합니다.

**Comment by SeungHoAhn** [comment]
좋은 생각입니다.

**Comment by childmild** [comment]
안드로이드 책도 정리할 책이 있는거같습니다.
이의견에 동의합니다.

**Comment by taeminhong** [comment]
**이 이슈는 WEP를 거치지 않고 다음 회의 안건으로 바로 올리겠습니다.**
지속적이고 주기적으로 일어나는 문제가 아니라 한 번 일을 처리하면 끝나는 단발적인 작업이기 때문입니다.
이런 이슈를 별도의 문서로 쓰려고 하면 시간과 노력은 많이 들면서 이로 인해 얻는 이득은 거의 없습니다.
이와는 달리 책을 보관하고 갱신하는 절차와 방법을 정의하거나 도서 관리자 임명 같은 이슈라면 WEP를 작성 하는 것이 도움이 되겠죠.

이처럼 모든 이슈가 WEP를 거쳐야 하는 것은 아닙니다.
불편하거나 맘에 들지 않는 점이 있으면 부담 갖지 마시고 이슈로 올려주세요.
관리자가 자세하게 안내해 드립니다.

**Comment by taeminhong** [comment]
버릴 책을 분류 중입니다.
모든 사람이 쉽게 볼 수 있도록 배치해 놓았습니다.
만약 폐기할 책이 있다면 책장에 꽂아주세요.
반대로 책장에 꽂혀있지만 폐기하면 안 되는 책은 빼서 위로 올려주세요.
목록 확정일은 12월 1일 금요일입니다.

![20171127_125552-small.jpg](https://trello-attachments.s3.amazonaws.com/5806c38c4223d96ea7c5dc58/5a1b8edb3bcada3ace63a402/27757c437f9df3d6b1b040b072506816/20171127_125552-small.jpg)

![20171123_185345-small.jpg](https://trello-attachments.s3.amazonaws.com/5806c38c4223d96ea7c5dc58/5a1b8edb3bcada3ace63a402/c5e94248f978d3ad504d2b4272790abd/20171123_185345-small.jpg)

**Comment by taeminhong** [comment]
12월 7일 책 정리를 끝냈습니다.
