### ISSUE TITLE
유니티 버전 파편화가 심합니다.

### ISSUE THREAD

**Issue by taeminhong** [kovidev/weps#5]
거의 모든 프로젝트가 각자 다른 버전의 유니티를 사용합니다.
해서 한 작업자가 여러 프로젝트를 빌드하려면 유니티를 2~4개씩 따로 설치를 해야 하는 상황이 벌어집니다.

[여기서](https://docs.google.com/spreadsheets/d/1Ojf2nh3MXdCbD2znTeOOL10Z-JVOnu9AbFbHn4yA7tc/edit?usp=sharing) 각 프로젝트가 사용하는 유니티 버전을 볼 수 있습니다.
만약 자신이 담당하고 있는 프로젝트가 빠졌거나 잘못된 정보가 있다면 수정 바랍니다.

기존에 만든 것은 놔두되, 앞으로 만들 프로젝트는 위 표에 나온 버전으로 한정하는 것을 조심스레 제안해봅니다.

**Comment by youchangCho** [comment]
버전을 한정 하는 것은 양면성을 가지고 있다는 것이 제 의견 입니다.
버전을 한정 할 경우 새로운 기능 사용에 대해서 제약이 있습니다.
또한 새로운 기능을 사용하기 위해서는 결국 파편화를 피할 수 없습니다.
 
하지만 버전을 동기화 해야 한다는 것에는 전적으로 동의 합니다. 

버전을 제한 하기 보다는 이전 프로젝트에 대하여 버전 종속이 없을 경우 최대한 안정적인 최신 버전으로 버전 업을 하는 것을 제안 합니다. 
특히 유지보수가 필요한 프로젝트는 향 후 를 위해서라도 버전업 관리를 해주는 것이 좋지 않을까 합니다.

**Comment by taeminhong** [comment]
WEP-0003이 승인 되었습니다.
저장소 관리자가 버전 파편화 문제를 담당합니다.
