### ISSUE TITLE
소스 저장소 백업 부재

### ISSUE THREAD

**Issue by taeminhong** [kovidev/weps#6]
아무도 서브버전 저장소 백업에 신경을 쓰지 않습니다.
이러다 불의의 사고로 회사의 지적 재산이 연기처럼 증발할 수 있습니다.
회사 내부와 외부, 최소 두 군데에 저장소 백업을 만들어야 합니다.
백업은 물리적으로 분리된 공간에 있어야 합니다.

**Comment by gegabal** [comment]
오!!! 불나서 다 날라갈까봐 걱정하는 사람이 나뿐이 아니었다는게  참으로 반갑네요.. 일단 저는 동의 합니다. 당연히 해야 하는 이슈라고 생각하고요. 이 건에 대해서 이미 여러번에 걸쳐서 전사적인 차원으로 건의도 해 보고 했는데 다들 반응이.. 맞아 그래야지.. 하고 끝났거든요. 시기가 딱 좋으니 구체화 시켜서 진행합시다. 일단 이번에 코비하우스 서버을 이전하면서 가비아IDC에 유휴 서버가 하나 생길거구요, 거기에 스토리지 추가해서 백업 하는걸로 하면 될 것 같네요. 시기는 대략 1월 중순 쯤 진행 하는 것으로 하죠. 쓸만한 백업 솔루션들을 좀 알아봅시다.

**Comment by youchangCho** [comment]
백업은 아무리 해도 과하지 않죠. 
SVN 외 레드마인, 현재 별도로 돌아가는 것들을 함께 이전 할 수 있으면 더 좋을거 같습니다.

**Comment by taeminhong** [comment]
60.196.157.175에 서브버전 미러를 시범 운영중입니다.
미러링을 수행하는 프로젝트는 다음과 같습니다.
Coex, KEPCO, KEPCO2, KOVIArchi3, KOVIKHR(4.15), Livart2-Kitchen, Prebuilt, RnA-1.4compatible, SIT-1.4compatible, younglim
동기화는 낮12시와 새벽 3시에 이루어집니다.
자신이 참여한 프로젝트의 미러가 문제없이 잘 돌아가는지 각자 확인해보세요.
