### ISSUE TITLE
Commit log 규격화를 제안 합니다

### ISSUE THREAD

**Issue by youchangCho** [kovidev/weps#8]
커밋 메시지를 규격화하면 협업 및 인수인계 비용이 줄어듭니다. 

# 동기 
우리 회사의 Commit message log 의 문제점은 다음과 같습니다. 

1. 현재 많은 프로젝트들의 svn commit log 를 보면 의미 없는 log가 너무 많습니다. 
2. 이런 log 들은 실제 유지보수 및 인수인계 과정에서 전혀 도움이 되지 않으며 결국 코드를 모두 보고 해석 해야 하는 문제가 발생 합니다. 
3. 의미 없는 로그 메시지와 하나의 commit에 너무 많은 변화로 인하여 어떤 부분이 수정 및 변경 되었는지 알 수 없습니다.
4. 지금 저 또한 제 마음대로 log 를 기입하고 있으며 누락된 내용으로 인하여 개발담당자인 '나' 조차 알아보기 힘든 상황이 되고 있습니다.

앞으로 진행 되는 프로젝트에 대하여 개발자들 간 내용을 빠르게 공유하고 인수인계 및 협업을 위해서라도 Log 규격화는 반드시 필요할 것이라 생각 됩니다. 

# 제안

많은 사람들이 사용하는 기본 규약 + 우리 회사만의 규약 을 지정 하여야 합니다.

한명이 강제적으로 정하는 것이 아니라 우리 회사에 맞는 로그 규격을 만들어야 합니다.

로그에 대한 규격은 최소한 기본적인 기준에는 맞춰야 한다는 의견 입니다. 

우리만의 Commit message 를 만들기 위해서는 경험이 많은 개발자의 많은 의견이 모아져야 한다고 생각합니다.

* 첫 행은 요약으로 길지 않고 간결하게 작성 되어야 합니다.
* 너무 많은 수정 후 한번에 커밋을 하지 않도록 합니다. 
* Redmine 등과 같은 이슈 트레커를 최대한 활용 하여 연계 하는것이 좋습니다.
* 내가 보는 로그가 아닌 다른 사람이 보는 로그라 생각하고 남겨야 합니다. 

정말 중요한 것은 commit message 를 귀찮아 하면 않됩니다. 

대충쓴 Commit message 는 결국 나에게 [야근+주말근무] 라는 화살이 되어 돌아 옵니다.

# 참조 사이트
commit message 는 [google](https://www.google.co.kr/search?dcr=0&ei=-PElWp2nIcWh0gTGibuYBA&q=%EC%BB%A4%EB%B0%8B+%EB%A9%94%EC%8B%9C%EC%A7%80&oq=%EC%BB%A4%EB%B0%8B+%EB%A9%94%EC%8B%9C%EC%A7%80&gs_l=psy-ab.3..0l5j0i5i30k1l2.3970.10003.0.10309.21.17.4.0.0.0.157.1611.0j12.13.0....0...1c.1.64.psy-ab..6.15.1520.6..35i39k1j0i131k1j0i8i30k1.131.CCBrkNQpuMk) 에 검색만 해도 엄청난 정보들이 나옵니다.

대표적으로 잘 정리 되어 있는 관련 사이트중 commit message 는 [여기](https://item4.github.io/2016-11-01/How-to-Write-a-Git-Commit-Message/) 나 [여기](http://www.haruair.com/blog/2683) 를 참고 하시면 됩니다.

**Comment by taeminhong** [comment]
하나의 글에 두 개의 주제가 있어 이견 조율에 어려움이 예상됩니다.
주석과 커밋메시지를 서로 다른 이슈로 분리하는 것을 부탁합니다.

**Comment by youchangCho** [comment]
이 글의 주제를 하나로 변경하였습니다.

**Comment by KimHwandeog** [comment]
찬성합니다 저 또한 당장 로그를 공유하는 사람이 없어 마음대로 작성하고 있는데 좋은 지표가 될것 같습니다.

**Comment by Dongjun-colt** [comment]
찬성합니다 저 또한 당장 로그를 공유하는 사람이 없어 마음대로 작성하고 있는데 좋은 지표가 될것 같습니다.

**Comment by gegabal** [comment]
셈플 포멧까지 제안을 해주면 더 좋을 것 같네요. 이미 사용하고 있는 포멧이라던가 혹은 생각하고 있던 포멧(아니면 위의 참고 링크에서 추천하는 형태라도)을 놓고 보면서 논의하면 더 좋을 듯.

**Comment by youchangCho** [comment]
저 같은 경우는 좀 중구 난방이긴 하지만 지키고 있는 포멧이 있습니다. 

File open 버그 이슈에 대한 예문 입니다.
```
* File Open filter 처리가 않되는 이슈를 해결 하였습니다.

이슈 #1234(레드마인 이슈넘버)
* Fileopen.cs 에 Filter 처리 로직을 추가 하였습니다. 
    - Filter 는 동작 했지만 모든 파일에 대한 필터가 함께 있어 이 부분을 삭제 하였습니다. 
```

대략 이런 식으로 사용 합니다. 
만일 코드에 대한 코맨트를 더 남겨야 한다고 생각 할 경우 함수 이름 등을 남깁니다.

**Comment by taeminhong** [comment]
위 조건을 대체로 만족하는 프로젝트는 svn://dev.kovi.com/SIT-1.4compatible 입니다.
제목은 간결하고 지었고 하나의 커밋에 하나의 변경만 있습니다. 혼잣말하듯 쓰지 않았고요.

반면교사로 삼을만한 프로젝트는 svn://60.196.157.234/sitSrc/trunk 입니다.
일단 빈 커밋 메시지가 너무 많고, 커밋 메시지를 보고 정확히 어떤 작업을 한건지 알기 어렵습니다.

**Comment by youchangCho** [comment]
각자 자신만의 Commit Message 를 남긴뒤 논의 하는 거도 나쁘지 않은거 같습니다. 
각자의 Message를 비교해 보고 좋은 방식만 따와서 우리만의 형식으로 만들어도 될거 같습니다.

**Comment by jennney** [comment]
하나의 커밋에 하나의 변경만 있어야 한다는건 중요한 원칙 같습니다. 
저만 해도 여러기능들을 처리 해놓고 한번에 커밋치면서 설명이 누락되는 코드들도 많고 어떤 코드들이 어떤 기능을 수정하려 바뀌는지 모르게 되기 때문입니다.

**Comment by youchangCho** [comment]
Commit Log(Message)를 남기는 방법에 대한 [가이드 라인](https://github.com/kovidev/weps/wiki/올바른-Commit-Log-작성-방법) 이 Wiki 에 기재 되었습니다.
다들 한번씩 읽어 보시고 자신이 남기는 방식과 어떤 차이가 있는지 비교해보시길 바랍니다.

**Comment by taeminhong** [comment]
제안자의 퇴사로 WEP를 작성할 사람이 없습니다. 이슈를 닫겠습니다.
