### ISSUE TITLE
Code 의 주석 규격화를 제안합니다.

### ISSUE THREAD

**Issue by youchangCho** [kovidev/weps#9]
주석을 규격화하면 코드의 가독성이 올라가고 효과적인 코드 관리가 가능해집니다.
더 나아가 협업 및 인수인계 비용도 줄어듭니다.

# 동기 
우리 회사의 주석의 문제점은 다음과 같습니다. 

1. 함수나 Class를 누가 만들었는지 뿐 아니라 무엇을 하며 어떤 데이터가 입력되고 출력 되는지 알 수가 없습니다.
2. 주석이 있지만 해석이 불가능 한 주석이 많습니다.
3. 주석이 없는 코드가 대부분 입니다.

# 제안
Commit message 와 동일하게 현재 많은 사람들이 사용하는 기본 규약  + 우리 회사만의 규약을 지정 하여야 합니다. 

우리만의 좋은 주석을 만들기 위해서는 경험이 많은 개발자의 의견이 모아져야 한다고 생각합니다.

필수 적인 기본 항목을 나열 하면 아래와 같습니다.
* 함수 및 Class 에 대한 설명이 필요합니다.
* 함수 및 Class 가 어떤 기능을 하는 것인지 알려주면 좋습니다.
     * 어떤 파라미터를 넣어야 하며 어떤 데이터가 나오는지 알려주면 더 좋겠죠.
* 미진된 부분 및 개선이 필요한 부분은 [todo:] 를 활용 합니다.
     * Visual studio 에서 Wroking list(작업 목록) 에 기제 됩니다.
* 상수에 대한 설명은 반드시 필요 합니다.

주석을 귀찮아 하면 않됩니다. 

대충쓴 주석은 결국 나에게 [야근+주말근무] 라는 화살이 되어 돌아 옵니다.

**Comment by youchangCho** [comment]
Commit log 와 같이 제가 사용하는 예문을 제시 하도록 하겠습니다. 

제가 남기는 형식입니다. 

추가 되는 로직이 있다면
```
//20171208 add ; index 를 받기 위한 변수를 추가 합니다. by imagej
int index = 0;
```
수정 되는 로직이 있다면
```
  //20171208 mod ; 조건을 변경 합니다. by imagej
  if(b == true)
//if(a == true)
```
삭제 되는 로직이 있다면
```
  //20171208 del ; 조건을 삭제 합니다. by imagej
  //if(a == true)
```

함수나 Class를 생성 할 경우 
```
///<summary>
/// 더하는 Class 입니다.
///</summary>
Class AddClass{
  
    /// <summary>
    /// 정수를 문자열로 변경 하는 테스트를 하는 로직 입니다.
    /// </summary>
    /// <param name="a">문자열로 변경할 int 형 정수</param>
    /// <returns>변환된 문자열</returns>
   private string TestFunction(int a)
   {
         return a.Tostring();
   }
}
```
summary 구문은 C# 일 경우 Class 나 함수 위에 /// 를 입력하면 자동 생성 됩니다. 

"이렇게 하자!" 가 아닙니다. 
"저는 이런 식으로 남기지만 다른 방법으로 우리만의 형식을 만들자!" 입니다. 

자신만의 스타일을 올린뒤 논의 하는거도 나쁘지 않은거 같네요.

**Comment by taeminhong** [comment]
주석에 작성자를 기재하면 안됩니다.
모든 코드는 [비자아적으로](https://www.google.co.kr/search?q=%EB%B9%84%EC%9E%90%EC%95%84%EC%A0%81+%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&dcr=0&ei=DhQqWuewIrGM8QfVzZS4AQ) 작성해야 합니다.
코드는 계속 변합니다. 작성자 이름이 붙은 코드를 만약 다른 사람이 수정하면 어떻게 해야 할까요?
작성자 이름을 바꿔야 할까요, 아니면 덧붙여야 할까요, 그냥 놔둬야 할까요?
뭐가 됐든 현명한 방법은 아닙니다.

코드를 누가, 언제, 무슨 이유로 작성했는지 알고 싶을 때는 [svn blame을](https://www.google.co.kr/search?client=firefox-b-ab&dcr=0&biw=1439&bih=740&tbm=isch&sa=1&ei=ehcqWqLyGobz8QXNmozYCg&q=svn+blame&oq=svn+blame&gs_l=psy-ab.3...0.0.0.54546.0.0.0.0.0.0.0.0..0.0....0...1c..64.psy-ab..0.0.0....0.VbSNqj09NQ0) 써야합니다.
작성자 기재는 버전관리도구를 사용하지 않았던 시절에서 유래한 나쁜 습관입니다.

**Comment by taeminhong** [comment]
코드를 삭제할 때 주석으로 만들면 안 됩니다.
다른 분들도 제발 그러지 말아 주세요. ㅠㅠ
맘 편히 삭제하세요. 언제든 삭제 내용을 볼 수 있고 복구도 쉽게 할 수 있습니다.
그러기 위해서 서브버전 같은 걸 쓰는 거니까요.

**Comment by taeminhong** [comment]
주석을 잘 쓰려면 아래 책 중에 적어도 한 권은 읽어야 한다고 생각합니다.

- [읽기 좋은 코드가 좋은 코드다](http://www.aladin.co.kr/shop/wproduct.aspx?ItemId=16108252)
- [프로그래밍 수련법](http://www.aladin.co.kr/shop/wproduct.aspx?ItemId=1711579)
- [코드 컴플리트](http://www.aladin.co.kr/shop/wproduct.aspx?ItemId=114392104)
- [클린코드](http://www.aladin.co.kr/shop/wproduct.aspx?ItemId=34083680)

맘 같아선 개발자 채용 요건에 넣어버리고 싶네요.

**Comment by youchangCho** [comment]
맞습니다. 전 버전관리도구를 사용하지 않았기 때문에 하던 버릇이 남아있습니다. 
주석남기는 버릇 또한 거기서 배운것이구요. 고쳐야 겠군요. 

코맨트는 하나만 남기도록 하죠 여러개를 따로 남기니 메일로 연속으로 날라오네요. 
위와같이 연속적인 코맨트는 좋지 않은듯 합니다.

**Comment by youchangCho** [comment]
좋은 주석을 작성하는 [가이드 라인](https://github.com/kovidev/weps/wiki/%EC%A2%8B%EC%9D%80-%EC%A3%BC%EC%84%9D%EC%9D%84-%EB%82%A8%EA%B8%B0%EB%8A%94-%EB%B0%A9%EB%B2%95)이 Wiki 에 기재 되었습니다.
다들 한번씩 읽어 보시고 자신이 남기는 주석과 어떻게 다른지 비교 해보시길 바랍니다.

**Comment by taeminhong** [comment]
제안자의 퇴사로 WEP를 작성할 사람이 없습니다. 이슈를 닫겠습니다.
